version: "3"
services:
  db:
    container_name: mysql_db_market
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pentaho_db_market
      - TZ=Asia/Jakarta

    ports:
      - "3303:3306"
    volumes:
      - ./import:/docker-entrypoint-initdb.d
      # - ./mysql-log:/var/log/mysqld.log
    # restart: always
